### ISSUE TITLE
Roadmap for v1.0

### ISSUE THREAD

**Issue by S1SYPHOS** [fundevogel/php-pcbis#2]
- [x] Move book-related stuff to `Class Book()`, see c6d80970535e8b5c370d953fbfbca57da1d547f8
- [x] ~~Make stuff chainable~~
- [x] Perfect audiobook support
